language: node_js
node_js:
- node
before_script:
- npm install -g gulp bower
- bower install
script: gulp
env:
  global:
  - ENCRYPTION_LABEL: 064c411d83d2
  - COMMIT_AUTHOR_EMAIL: mauricio@navarromiranda.mx
